export const FIELD_LABELS: Record<string, string> = {
  // Original Mapping from Excel "Actual Field Name"
  request_date: "Request Date",
  request_docs: "Request Docs?",
  policy_type: "Policy Type",
  renewal_date: "Renewal Date",
  current_carrier: "Current Carrier",
  current_premium: "Current Premium",
  renewal_premium: "Renewal Premium",
  target_date: "Target Date",
  docs_received: "Docs Received?",
  ezlynx_updated: "EZLynx Updated?",
  quoted_premium: "Quoted Premium",
  savings: "Savings",
  agency_fee: "Agency Fee",
  payment_method: "Payment Method",
  bound_premium: "Bound Premium",
  commission: "Commission",
  prior_term_cancelled: "Prior Term Cancelled?",
  x_date: "X-Date",

  // Internal Keys to Excel Logic
  target_completion_date: "Target Date",
  docs_saved: "Docs Saved?",
  info_received: "Docs Received?",
  required_documents_received: "Docs Received?",
  finalized_quote: "Quote Finalized?",
  quote_finalized: "Quote Finalized?",
  carrier_quote_sent: "Quoted Carrier",
  carrier_name: "Quoted Carrier",
  payment_frequency: "Payment Frequency",
  policy_number: "Policy Number",
  expected_commission: "Commission",
  policy_docs_sent: "Docs Sent?",
  docs_sent_to_client: "Docs Sent?",
  docs_saved_ezlynx: "Docs Saved?",
  policy_docs_saved: "Docs Saved?",
  business_profile_updated_ezlynx: "EZLynx Updated?",
  quoted_multiple_carriers: "Quoted Multiple Carriers?",
  autopay_setup: "Autopay Setup?",
  autopay_enabled: "Autopay Enabled?",
  paid_for_renewal: "Policy Paid?",
  policy_paid: "Policy Paid?",
  savings_amount: "Savings",
  agency_fees: "Agency Fee",
  cancelled_prev_carrier: "Prior Term Cancelled?",
  cancelled_previous_carrier: "Prior Term Cancelled?",
  documents_saved_filecenter: "Docs Saved?",
  cancellation_reason: "Cancellation Reason",
  reason_not_bound: "Reason Not Bound",
  notes: "Notes/Details",

  // Intake Form overrides
  claims_last_5_years: "Claims (Last 5 Years)",
  claims_count: "Number of Claims",
  has_basement: "Has Basement?",
  basement_type: "Basement Type",
  has_alarm: "Centralized Alarm/Security?",
  paid_by_escrow: "Paid by Escrow?",
  mortgage_clause: "Mortgagee Clause",
  violations_last_5_years: "Violations (Last 5 Years)",
  violation_count: "Number of Violations",
  good_driver_discount: "Good Driver Discount?",
  make_model: "Vehicle (Make + Model)",
  primary_use: "Primary Use",
  annual_miles: "Estimated Annual Miles"
};
